ALTER TYPE "app"."audit_action" ADD VALUE 'tenant.renamed';--> statement-breakpoint
ALTER TYPE "app"."audit_action" ADD VALUE 'tenant.suspended';--> statement-breakpoint
ALTER TYPE "app"."audit_action" ADD VALUE 'tenant.reactivated';--> statement-breakpoint
ALTER TABLE "app"."audit_entry" DROP CONSTRAINT "audit_entry_shape";--> statement-breakpoint
ALTER TABLE "app"."audit_entry" ADD CONSTRAINT "audit_entry_shape" CHECK ((case "app"."audit_entry"."action"::text
    when 'member.invited' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{role}'::text[] = '{}'::jsonb and "app"."audit_entry"."data" ->> 'role' in ('admin', 'dispatcher', 'driver')
    when 'member.role_changed' then "app"."audit_entry"."subject_user_id" <> '' and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and "app"."audit_entry"."data" ->> 'from' in ('admin', 'dispatcher', 'driver') and "app"."audit_entry"."data" ->> 'to' in ('admin', 'dispatcher', 'driver')
    when 'member.removed' then "app"."audit_entry"."subject_user_id" <> '' and "app"."audit_entry"."data" - '{role}'::text[] = '{}'::jsonb and "app"."audit_entry"."data" ->> 'role' in ('admin', 'dispatcher', 'driver')
    when 'settings.airport_wait_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and (case when jsonb_typeof("app"."audit_entry"."data" -> 'from') = 'number' and ("app"."audit_entry"."data" ->> 'from') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'from')::integer between 1 and 1440 else false end) and (case when jsonb_typeof("app"."audit_entry"."data" -> 'to') = 'number' and ("app"."audit_entry"."data" ->> 'to') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'to')::integer between 1 and 1440 else false end)
    when 'settings.elsewhere_wait_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and (case when jsonb_typeof("app"."audit_entry"."data" -> 'from') = 'number' and ("app"."audit_entry"."data" ->> 'from') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'from')::integer between 1 and 1440 else false end) and (case when jsonb_typeof("app"."audit_entry"."data" -> 'to') = 'number' and ("app"."audit_entry"."data" ->> 'to') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'to')::integer between 1 and 1440 else false end)
    when 'settings.time_zone_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'from') = 'string' and length("app"."audit_entry"."data" ->> 'from') between 1 and 64 and jsonb_typeof("app"."audit_entry"."data" -> 'to') = 'string' and length("app"."audit_entry"."data" ->> 'to') between 1 and 64
    when 'client.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{clientId,kind}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'clientId') = 'string' and "app"."audit_entry"."data" ->> 'clientId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and "app"."audit_entry"."data" ->> 'kind' in ('agency', 'hotel', 'individual')
    when 'client.name_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{clientId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'clientId') = 'string' and "app"."audit_entry"."data" ->> 'clientId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'client.kind_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{clientId,from,to}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'clientId') = 'string' and "app"."audit_entry"."data" ->> 'clientId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and "app"."audit_entry"."data" ->> 'from' in ('agency', 'hotel', 'individual') and "app"."audit_entry"."data" ->> 'to' in ('agency', 'hotel', 'individual')
    when 'driver.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{driverId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 7 and "app"."audit_entry"."data" -> 'fields' <@ '["name","kind","phone","drivingLicenceExpiresOn","transportLicenceExpiresOn","memberUserId","mustAccept"]'::jsonb
    when 'driver.field_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{driverId,field}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'field') = 'string' and "app"."audit_entry"."data" ->> 'field' in ('name', 'kind', 'phone', 'drivingLicenceExpiresOn', 'transportLicenceExpiresOn', 'memberUserId', 'mustAccept')
    when 'vehicle.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{vehicleId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 6 and "app"."audit_entry"."data" -> 'fields' <@ '["registrationPlate","kind","registrationExpiresOn","technicalInspectionExpiresOn","insuranceExpiresOn","description"]'::jsonb
    when 'vehicle.field_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{vehicleId,field}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'field') = 'string' and "app"."audit_entry"."data" ->> 'field' in ('registrationPlate', 'kind', 'registrationExpiresOn', 'technicalInspectionExpiresOn', 'insuranceExpiresOn', 'description')
    when 'vehicle.archived' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{vehicleId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'tenant.renamed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" = '{}'::jsonb
    when 'tenant.suspended' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" = '{}'::jsonb
    when 'tenant.reactivated' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" = '{}'::jsonb
    else false end) is true);
--> statement-breakpoint
-- Rename runs as transferpro_platform. The role can append and cannot read the log back.
-- 0012 is separate from the enum's first use: this check compares action::text,
-- so the new labels are not cast to the enum in the migration that adds them.
GRANT USAGE ON SCHEMA "audit" TO "transferpro_platform";
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION "audit"."append_entry"(text, text, text, jsonb) TO "transferpro_platform";
