-- One email on each Driver. A linked row copies the sign-in email before the
-- check that requires it. Unlinked rows stay null. The view is the privileged
-- read: the owner selects auth.user, and the app role is granted the view only.
ALTER TABLE "app"."audit_entry" DROP CONSTRAINT "audit_entry_shape";--> statement-breakpoint
ALTER TABLE "app"."drivers" ADD COLUMN "email" text;--> statement-breakpoint
UPDATE "app"."drivers" AS d
SET "email" = u."email"
FROM "auth"."user" AS u
WHERE d."member_user_id" = u."id"
  AND d."email" IS NULL;--> statement-breakpoint
ALTER TABLE "app"."audit_entry" ADD CONSTRAINT "audit_entry_shape" CHECK ((case "app"."audit_entry"."action"::text
    when 'member.invited' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{role}'::text[] = '{}'::jsonb and "app"."audit_entry"."data" ->> 'role' in ('admin', 'dispatcher', 'driver')
    when 'member.role_changed' then "app"."audit_entry"."subject_user_id" <> '' and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and "app"."audit_entry"."data" ->> 'from' in ('admin', 'dispatcher', 'driver') and "app"."audit_entry"."data" ->> 'to' in ('admin', 'dispatcher', 'driver')
    when 'member.removed' then "app"."audit_entry"."subject_user_id" <> '' and "app"."audit_entry"."data" - '{role}'::text[] = '{}'::jsonb and "app"."audit_entry"."data" ->> 'role' in ('admin', 'dispatcher', 'driver')
    when 'settings.airport_wait_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and (case when jsonb_typeof("app"."audit_entry"."data" -> 'from') = 'number' and ("app"."audit_entry"."data" ->> 'from') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'from')::integer between 1 and 1440 else false end) and (case when jsonb_typeof("app"."audit_entry"."data" -> 'to') = 'number' and ("app"."audit_entry"."data" ->> 'to') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'to')::integer between 1 and 1440 else false end)
    when 'settings.elsewhere_wait_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and (case when jsonb_typeof("app"."audit_entry"."data" -> 'from') = 'number' and ("app"."audit_entry"."data" ->> 'from') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'from')::integer between 1 and 1440 else false end) and (case when jsonb_typeof("app"."audit_entry"."data" -> 'to') = 'number' and ("app"."audit_entry"."data" ->> 'to') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'to')::integer between 1 and 1440 else false end)
    when 'settings.time_zone_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'from') = 'string' and length("app"."audit_entry"."data" ->> 'from') between 1 and 64 and jsonb_typeof("app"."audit_entry"."data" -> 'to') = 'string' and length("app"."audit_entry"."data" ->> 'to') between 1 and 64
    when 'settings.operational_day_start_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{from,to}'::text[] = '{}'::jsonb and (case when jsonb_typeof("app"."audit_entry"."data" -> 'from') = 'number' and ("app"."audit_entry"."data" ->> 'from') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'from')::integer between 0 and 8 else false end) and (case when jsonb_typeof("app"."audit_entry"."data" -> 'to') = 'number' and ("app"."audit_entry"."data" ->> 'to') ~ '^[0-9]+$' then ("app"."audit_entry"."data" ->> 'to')::integer between 0 and 8 else false end)
    when 'client.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{clientId,kind}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'clientId') = 'string' and "app"."audit_entry"."data" ->> 'clientId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and "app"."audit_entry"."data" ->> 'kind' in ('agency', 'hotel', 'individual')
    when 'client.name_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{clientId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'clientId') = 'string' and "app"."audit_entry"."data" ->> 'clientId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'client.kind_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{clientId,from,to}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'clientId') = 'string' and "app"."audit_entry"."data" ->> 'clientId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and "app"."audit_entry"."data" ->> 'from' in ('agency', 'hotel', 'individual') and "app"."audit_entry"."data" ->> 'to' in ('agency', 'hotel', 'individual')
    when 'driver.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{driverId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 8 and "app"."audit_entry"."data" -> 'fields' <@ '["name","kind","phone","email","drivingLicenceExpiresOn","transportLicenceExpiresOn","memberUserId","mustAccept"]'::jsonb
    when 'driver.field_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{driverId,field}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'field') = 'string' and "app"."audit_entry"."data" ->> 'field' in ('name', 'kind', 'phone', 'email', 'drivingLicenceExpiresOn', 'transportLicenceExpiresOn', 'memberUserId', 'mustAccept')
    when 'vehicle.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{vehicleId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 6 and "app"."audit_entry"."data" -> 'fields' <@ '["registrationPlate","kind","registrationExpiresOn","technicalInspectionExpiresOn","insuranceExpiresOn","description"]'::jsonb
    when 'vehicle.field_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{vehicleId,field}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'field') = 'string' and "app"."audit_entry"."data" ->> 'field' in ('registrationPlate', 'kind', 'registrationExpiresOn', 'technicalInspectionExpiresOn', 'insuranceExpiresOn', 'description')
    when 'vehicle.archived' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{vehicleId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'location.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{locationId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'locationId') = 'string' and "app"."audit_entry"."data" ->> 'locationId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 3 and "app"."audit_entry"."data" -> 'fields' <@ '["name","kind","address"]'::jsonb
    when 'location.field_changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{locationId,field}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'locationId') = 'string' and "app"."audit_entry"."data" ->> 'locationId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'field') = 'string' and "app"."audit_entry"."data" ->> 'field' in ('name', 'kind', 'address')
    when 'location.archived' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{locationId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'locationId') = 'string' and "app"."audit_entry"."data" ->> 'locationId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'transfer.created' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{transferId,rideId,clientId,startLocationId,endLocationId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'transferId') = 'string' and "app"."audit_entry"."data" ->> 'transferId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'rideId') = 'string' and "app"."audit_entry"."data" ->> 'rideId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'clientId') = 'string' and "app"."audit_entry"."data" ->> 'clientId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'startLocationId') = 'string' and "app"."audit_entry"."data" ->> 'startLocationId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'endLocationId') = 'string' and "app"."audit_entry"."data" ->> 'endLocationId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 11 and "app"."audit_entry"."data" -> 'fields' <@ '["pickupAt","passengerCount","guestName","flightNumber","price","payment","airportMark","luggageCount","childSeatCount","note","tabla"]'::jsonb
    when 'ride.assigned' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{rideId,driverId,vehicleId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'rideId') = 'string' and "app"."audit_entry"."data" ->> 'rideId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 4 and "app"."audit_entry"."data" -> 'fields' <@ '["state","driverId","vehicleId","mustAccept"]'::jsonb
    when 'ride.accepted' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{rideId,driverId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'rideId') = 'string' and "app"."audit_entry"."data" ->> 'rideId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 1 and "app"."audit_entry"."data" -> 'fields' <@ '["state"]'::jsonb
    when 'ride.accepted_by_phone' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{rideId,driverId,fields}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'rideId') = 'string' and "app"."audit_entry"."data" ->> 'rideId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fields') = 'array' and jsonb_array_length("app"."audit_entry"."data" -> 'fields') between 1 and 1 and "app"."audit_entry"."data" -> 'fields' <@ '["state"]'::jsonb
    when 'roster.assigned' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{rosterDate,driverId,vehicleId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'rosterDate') = 'string' and "app"."audit_entry"."data" ->> 'rosterDate' ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$' and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'roster.changed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{rosterDate,driverId,fromVehicleId,toVehicleId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'rosterDate') = 'string' and "app"."audit_entry"."data" ->> 'rosterDate' ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$' and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'fromVehicleId') = 'string' and "app"."audit_entry"."data" ->> 'fromVehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'toVehicleId') = 'string' and "app"."audit_entry"."data" ->> 'toVehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'roster.cleared' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" - '{rosterDate,driverId,vehicleId}'::text[] = '{}'::jsonb and jsonb_typeof("app"."audit_entry"."data" -> 'rosterDate') = 'string' and "app"."audit_entry"."data" ->> 'rosterDate' ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$' and jsonb_typeof("app"."audit_entry"."data" -> 'driverId') = 'string' and "app"."audit_entry"."data" ->> 'driverId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and jsonb_typeof("app"."audit_entry"."data" -> 'vehicleId') = 'string' and "app"."audit_entry"."data" ->> 'vehicleId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    when 'tenant.renamed' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" = '{}'::jsonb
    when 'tenant.suspended' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" = '{}'::jsonb
    when 'tenant.reactivated' then "app"."audit_entry"."subject_user_id" is null and "app"."audit_entry"."data" = '{}'::jsonb
    else false end) is true);--> statement-breakpoint
ALTER TABLE "app"."drivers" ADD CONSTRAINT "drivers_email" CHECK ("app"."drivers"."email" is null or ("app"."drivers"."email" = btrim("app"."drivers"."email") and length("app"."drivers"."email") between 3 and 254 and position('@' in "app"."drivers"."email") > 1 and position(' ' in "app"."drivers"."email") = 0));--> statement-breakpoint
ALTER TABLE "app"."drivers" ADD CONSTRAINT "drivers_email_when_linked" CHECK ("app"."drivers"."member_user_id" is null or "app"."drivers"."email" is not null);--> statement-breakpoint
CREATE VIEW "app"."driver_sign_in_email" WITH (security_barrier = true, security_invoker = false) AS (
  select "auth"."member"."user_id", "auth"."user"."email"
  from "auth"."member"
  inner join "auth"."user" on "auth"."user"."id" = "auth"."member"."user_id"
  where "auth"."member"."organization_id" = app.current_tenant_id()::text
    and "auth"."member"."role" = 'driver'
);--> statement-breakpoint
REVOKE ALL ON "app"."driver_sign_in_email" FROM PUBLIC;--> statement-breakpoint
GRANT SELECT ON "app"."driver_sign_in_email" TO "transferpro_app";