import { expect, test } from '@playwright/test'
import { seedTenant, seedUserWithoutMembership } from './fixtures/seed'
import { invite, signIn, signOut } from './fixtures/ui'

test('an existing account signs in on the invite page and joins as a driver', async ({ page }) => {
  const tenant = await seedTenant('invite-existing')
  const existing = await seedUserWithoutMembership('invite-existing')
  await signIn(page, tenant.adminEmail, tenant.password, tenant.name)
  const link = await invite(page, existing.email, 'Vozač')
  await signOut(page)

  await page.goto(link)
  await expect(page.getByRole('heading', { level: 1, name: 'Prihvati pozivnicu' })).toBeVisible()
  await expect(page.getByText('Već imate račun. Prijavite se da biste prihvatili pozivnicu.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Otvori račun', exact: true })).toHaveCount(0)
  await page.getByLabel('E-pošta').fill(existing.email)
  await page.getByLabel('Lozinka').fill(existing.password)
  await page.getByRole('button', { name: 'Prijavi se i prihvati', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: tenant.name })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Odjeljci' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Revizijski zapisnik' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Dokumenti koji istječu' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Pozovi člana' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Članovi' })).toHaveCount(0)
  await expect(page.getByText('Samo administrator može ovo promijeniti.')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Postavke' })).toHaveCount(0)
})

test('an existing account signs in on the invite page and joins as a dispatcher', async ({ page }) => {
  const tenant = await seedTenant('invite-existing-disp')
  const existing = await seedUserWithoutMembership('invite-existing-disp')
  await signIn(page, tenant.adminEmail, tenant.password, tenant.name)
  const link = await invite(page, existing.email, 'Dispečer')
  await signOut(page)

  await page.goto(link)
  await expect(page.getByText('Već imate račun. Prijavite se da biste prihvatili pozivnicu.')).toBeVisible()
  await page.getByLabel('E-pošta').fill(existing.email)
  await page.getByLabel('Lozinka').fill(existing.password)
  await page.getByRole('button', { name: 'Prijavi se i prihvati', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: tenant.name })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Odjeljci' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Pozovi člana' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Članovi' })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Postavke' })).toHaveCount(0)
  await expect(page.getByText('Samo administrator može ovo promijeniti.')).toHaveCount(0)
  await expect(page.getByText('Primjer vremena')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Dokumenti koji istječu' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Revizijski zapisnik' })).toHaveCount(0)
})

test('an existing account signs in on the invite page and joins as an administrator', async ({ page }) => {
  const tenant = await seedTenant('invite-existing-admin')
  const existing = await seedUserWithoutMembership('invite-existing-admin')
  await signIn(page, tenant.adminEmail, tenant.password, tenant.name)
  const link = await invite(page, existing.email, 'Administrator')
  await signOut(page)

  await page.goto(link)
  await expect(page.getByText('Već imate račun. Prijavite se da biste prihvatili pozivnicu.')).toBeVisible()
  await page.getByLabel('E-pošta').fill(existing.email)
  await page.getByLabel('Lozinka').fill(existing.password)
  await page.getByRole('button', { name: 'Prijavi se i prihvati', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: tenant.name })).toBeVisible()
  await expect(page.getByText('Primjer vremena')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Dokumenti koji istječu' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Revizijski zapisnik' })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Pozovi člana' })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Postavke' })).toHaveCount(0)

  const sections = page.getByRole('navigation', { name: 'Odjeljci' })
  await sections.getByRole('link', { name: 'Postavke', exact: true }).click()
  const tabs = page.getByRole('navigation', { name: 'Postavke' })
  await tabs.getByRole('link', { name: 'Organizacija', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\/tenant$/)
  await expect(page.getByRole('region', { name: 'Postavke' }).getByRole('button', { name: 'Spremi', exact: true })).toBeVisible()
  await tabs.getByRole('link', { name: 'Članovi', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\/members$/)
  await expect(page.getByRole('region', { name: 'Pozovi člana' })).toBeVisible()
})
